spring:
  application:
    name: GERENCIAMENTO-LIVRO
  data:
    mongodb:
      uri: mongodb://localhost:27017/livraria
server:
  port: 8082
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
